### ISSUE TITLE
fix ^C handling

### ISSUE THREAD

**Issue by stsp** [dosemu2/comcom32#20]
Currently it just terminates comcom32.
Should instead abort the current command.

**Comment by jschwartzenberg** [comment]
Having ^D do something like what ^C does now might be useful, especially if the DOSEMU2 window then automatically closes (similar to a terminal window).

**Comment by stsp** [comment]
^D can do exit if the edit buffer is
empty, otherwise it does Enter.
Please open another ticket, its
unrelated to ^C.
But I would suggest to just do exit
by hands.

**Comment by stsp** [comment]
This is fixed.
