### ISSUE TITLE
dir /P does not pause

### ISSUE THREAD

**Issue by FelixGruetzmacher** [dosemu2/comcom32#35]
When typing dir /P in a somewhat crowded directory, counter to my expectations, there are no pauses, so the entire thing just scrolls past.
dir | more does the exact same thing on the first run.
On subsequent runs, interestingly, dir | more produces no output!
Context:
This is happening when logged in via putty (on Windows) to my Linux server.
Ubuntu 18.04
dosemu2-2.0pre8

**Comment by stsp** [comment]
This sound like comcom32 problem, but
pre8 is not bundled with comcom32.
So I suppose something is wrong with that
report.

**Comment by FelixGruetzmacher** [comment]
I installed using apt-get install dosemu2 and got comcom32 and fdpp.
I experimentally booted into the old Freedos bundle that came with the old
Dosemu. That solved the dir /P issue but broke compatibility with some
games.
If fdpp and comcom32 is not the recommended config, what is?
Btw thanks for the amazing emulator!

Am Mi., 11. März 2020 um 16:17 Uhr schrieb Stas Sergeev <
notifications@github.com>:

**Comment by stsp** [comment]
> I installed using apt-get install dosemu2 and got comcom32 and fdpp.

OK, but this is not pre8, just a nightly git build.

> If fdpp and comcom32 is not the recommended config, what is?

It is recommended, unless you want too much from
command.com. :) In this case you can get freecom.exe
from freedos and put it to c:\command.com to solve
the problem. dosemu2 always prefers what user adds
to what is by default.
I agree that /P is a basic thing that should work, and
I'll see about implementing it. Not so much about
"more" command... yet.

**Comment by stsp** [comment]
I.e. you don't need full freedos - just put any
command.com to `~/.dosemu/drive_c` and
this is it. It may be freecom.exe or for example
4dos.exe, which is much better than freecom.

**Comment by FelixGruetzmacher** [comment]
Thanks for clarifying! This helps a lot!
Full Freedos is out of the question for me as that kernel won't run some
games I don't want to miss, such as Level 9's Time And Magik trilogy or the
Silver Cloud. Interestingly, fdpp has no problem whatsoever with those.
Whoever is behind that kernel did an amazing job.

Am Mi., 11. März 2020 um 17:06 Uhr schrieb Stas Sergeev <
notifications@github.com>:

**Comment by stsp** [comment]
Its very pleasant to hear that fdpp achieved
its main goal. You can always track its progress
here:
https://github.com/stsp/fdpp/releases

**Comment by haenschen** [comment]
As stated in #61 I can confirm this issue on ubuntu 22.04 / pre9 with comcomr32 0.1~alpha3-170-c870111+202207101546~ubuntu22.04.1

**Comment by stsp** [comment]
Should now be fixed.

**Comment by haenschen** [comment]
Can confirm, thanks
