### ISSUE TITLE
WPDOS cannot find command.com

### ISSUE THREAD

**Issue by emendelson** [dosemu2/comcom32#37]
**Describe the bug**
In WordPerfect for DOS (5.1 or 6.2), the Go to DOS and DOS Command features cannot find COMMAND.COM and therefore don't function. This is with default settings; COMSPEC is defined in the environment as G:\COMMAND.COM (which exists).

**To Reproduce**
Run any version of WPDOS. Use Ctrl-F1, Go to DOS. The window goes blank for a moment, then returns. To see exactly what the problem is, use Ctrl-F1, DOS Command, and enter "pause" or "dir" or any other command; WP 6.2 returns a message "Can't find COMMAND.COM"; WP 5.1 displays the "Press any key to continue" message but doesn't run the command.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by emendelson** [comment]
Thank you! This means that if I use "sudo apt" to update dosemu2 tomorrow, the fixed version will get installed?

**Comment by stsp** [comment]
I updated the package repository.

**Comment by emendelson** [comment]
> 
> 
> I updated the package repository.

And I just installed it. Thank you.

**Comment by andrewbird** [comment]
I only just noticed you fixed this, as it seems when its issue was moved across projects the notifications stopped for me. Anyway, well done!

**Comment by stsp** [comment]
That likely means you are not watching
comcom32.

**Comment by andrewbird** [comment]
>That likely means you are not watching
comcom32.

Yep, it seems you are quite right! I wonder why not, I thought I was. Thanks!
