### ISSUE TITLE
CLS doesn't clear the screen in some video modes

### ISSUE THREAD

**Issue by emendelson** [dosemu2/comcom32#38]
**Describe the bug**
The CLS command correctly clears the screen in the default video mode (3 = co80). It doesn't clear the screen in many (maybe all) other video modes.

**To Reproduce**
Steps to reproduce the behaviour:

`xmode -mode 7`  
`dir`  
`cls`

The dosemu prompt appears at the top of the screen, but the directory listing produced by the dir command isn't cleared.

**Comment by stsp** [comment]
Yes, comcom32 feels very bad in any
mode but 3.

**Comment by stsp** [comment]
Should now be fixed.
Please open ticket in an  appropriate
projects if possible, so that I don't move
them around.

**Comment by emendelson** [comment]
Thank you - I didn't realize that this belonged in comcom32. I'll know better next time.

**Comment by emendelson** [comment]
I'm not sure you care, but this fix doesn't have any effect in Ubuntu Mate, which uses a fork of the old gnome 2 environment for its desktop (though I don't know why this should matter). I've been experimenting by building in Ubuntu Mate just because it's lighter-weight than standard Ubuntu, and a bit faster in a VM. I upgraded dosemu2 and comcom32 to the latest version a few minutes ago, and tried the "steps to reproduce" in the first post, and the problem was still there.

Again, probably not worth spending any time on.

**Comment by stsp** [comment]
I suspect a user error.

**Comment by emendelson** [comment]
This particular user has made many errors before. Will test on a fresh Ubuntu Mate system later this week.

**Comment by emendelson** [comment]
Yes, user error. I wiped the Ubuntu Mate VM and set up another one, and the problem does not occur.
