### ISSUE TITLE
DIR shows 0 byte(s) free

### ISSUE THREAD

**Issue by stsp** [dosemu2/comcom32#44]
See https://github.com/dosemu2/dosemu2/issues/1317#issuecomment-710700536

**Comment by andrewbird** [comment]
Seems that full_filespec is lower case, this little patch allows it to show free space (clamped at 2GB) 
~~~
-  getdfree(full_filespec[0]-'A'+1, &df);
+  getdfree(full_filespec[0]-'a'+1, &df);
~~~

**Comment by stsp** [comment]
Thanks, that's the correct fix.

**Comment by stsp** [comment]
For me it returns 1Gb though, not 2.

**Comment by andrewbird** [comment]
Yes, that's the same for me. On my system it's clamped at almost 2GB, but the display is 1GB
~~~
>>> 2147450880/1024/1024/1024
1.999969482421875
~~~

Is it the sign on the printf format `(%15lli)`?

**Comment by andrewbird** [comment]
I rather think it's just truncation, not rounding.

**Comment by stsp** [comment]
Yep, should now be better.
