### ISSUE TITLE
environment variable editing

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/comcom32#46]
First: I did install comcom32 "manually", that is, I extracted comcom32.exe from:

https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa/+files/comcom32_0.1~alpha2-130-dd29ffa+202011211542~ubuntu21.04.1_amd64.deb

and copied it to .dosemu/drive_c, renaming it to COMMAND.COM. I simply don't want to add any repositories to my debian installation.

The problem with comcom32:
1. when I enter "set DPMILDR=" I expect the environment variable to disappear. It doesn't, it's still there, with no "contents"
2. when I enter "set path=c:\hx\bin;%path%",  then the PATH variable isn't changed, but a new variable created, so the environment contains both "PATH" and "path" variables ( the latter not being used for executable searches ).

It might be that this is "expected behavior", but in my eyes it's incompatible and needs to be fixed.

**Comment by stsp** [comment]
Should now be fixed.
