### ISSUE TITLE
fdnpkg reset PATH?

### ISSUE THREAD

**Issue by j2969719** [dosemu2/comcom32#49]
i have a userhook.bat in drive_c with a custom PATH
after the first launch of fdnpkg, for some reason it is reset back to D:\DOSEMU;F:\

if i put 4dos or freecom in the drive_c  root, is works fine

[drive_c.tar.gz](https://github.com/dosemu2/comcom32/files/5646584/drive_c.tar.gz)

**Comment by stsp** [comment]
That's because you had to use `path`
not `set` to set PATH.
But I made it to work in both cases.
