### ISSUE TITLE
Environment variable contents are upcased

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/comcom32#50]
A batch file that sets the var CC and then echos it
~~~
set CC=tcc
echo %CC%
~~~

##### with Comcom32 it's upcased
~~~
G:\>echo TCC
TCC
~~~

##### with FreeCOM the case is preserved
~~~
G:\>echo tcc
tcc
~~~

Impact - prevents passing case sensitive switches via env vars.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
I just waited for the PPA to update, seems fine now. Thanks.
