### ISSUE TITLE
Budokan doesn't start

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/comcom32#58]
**Describe the bug**
The game doesn't start.

**To Reproduce**
Run the game.

**Attach program/game binaries or provide an URL**
[budocan.tar.gz](https://github.com/dosemu2/dosemu2/files/8952383/budocan.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8952385/boot.log)

**A regression?**
unknown

**Comment by stsp** [comment]
Fixed.
