### ISSUE TITLE
apply loadfix automatically

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/comcom32#59]
**Describe the bug**
Running Lemmings crashes DOSEMU.
```
ERROR: general protection at 0x7f5a60721196: a5
ERROR: unexpected CPU exception 0x0c err=0x00000000 cr2=00000000 while in vm86 (DOS)
Terminated with signal 4
```

**To Reproduce**
Run the game.

**Attach program/game binaries or provide an URL**
[lemming.tar.gz](https://github.com/dosemu2/dosemu2/files/9067127/lemming.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9067132/boot.log)

**A regression?**
Seems so, although it might be due to a different version of Lemmings.

**Comment by stsp** [comment]
@ecm-pushbx As an author
of loadfix in comcom32, maybe
you would like to implement
also an autodetection?

**Comment by stsp** [comment]
Seems to work quite nice!
I guess comcom32 can also
be responsible for applying
the binary patches to a progs.

**Comment by jschwartzenberg** [comment]
> I guess comcom32 can also
> be responsible for applying
> the binary patches to a progs.

Would this also work if not the main executable needs a patch but some other file (like a sound driver)?

**Comment by stsp** [comment]
> Would this also work if not the main executable needs a patch but some other file (like a sound driver)?

Likely not. :(
But still we aim for "majority" and
not "all".
