### ISSUE TITLE
Copy doesn't allow wildcard * on destination

### ISSUE THREAD

**Issue by haenschen** [dosemu2/comcom32#62]
**Describe the bug**
Copy doesn't allow wildcard * on destination

**To Reproduce**
```
copy file1.1 *.dat
Illegal wildcard on destination
```
**Expected behaviour**
```
copy file1.1 *.dat
file1.1 =>> file1.dat

```

**Attach program/game binaries or provide an URL**
Works with freecom and MS-DOS command.com

**A regression?**
With comcom32

**Comment by stsp** [comment]
Added some hackish wildcard support.

**Comment by haenschen** [comment]
Thanks. I tested it, but it doesn't work as expected. Let's say I'm in a directory `test1` and want to copy files from a subdirectory `test2` into this one:
`copy test2\*.* *.*`
Fails with
`Unable to open destination file - c:\TEST1\*xt.*u`

**Comment by haenschen** [comment]
To be fair, this case wasn't represented in my initial report :)

**Comment by haenschen** [comment]
Ah, I see. So it has to do with a previous command. To reproduce, create a batch file
```
if exist test2\file1.1 copy test2\file1.1 file1.dat
copy test2\*.* *.*
```
and call it.


Provided the first if clause succeeds the second copy will fail with 
```
Unable to open destination file - c:\TEST1\*le1.*
```
Test case attached
[copytest.zip](https://github.com/dosemu2/comcom32/files/9575910/copytest.zip)

**Comment by stsp** [comment]
Should now be fixed.
