### ISSUE TITLE
DIR (using int21/7303) non longer reports correct space

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/comcom32#69]
Since 2a0ee04967b79157aede01459ea9d7d667c2f8dc DIR either always falls back to int21/36 or returns gibberish values from int21/7303

**Comment by andrewbird** [comment]
It seems the segments aren't set.
~~~
fdpp: System call (21h): 7303                                                   
fdpp: in 7303 DS = 0                                                            
fdpp: in 7303 ES = 0                                                            
fdpp: in 7303 CX = 44                                                           
fdpp: in 7303 after                                                             
fdpp: in DosGetExtFree 0 'þ'                                                    
~~~
I have to leave this to you @stsp as I don't understand all this DPMI stuff.

**Comment by stsp** [comment]
Thanks, could you please check the fix?

**Comment by andrewbird** [comment]
Thanks, it's working now.

**Comment by stsp** [comment]
That's a stupid fix actually.
Could you please change that code
to statfs()?

**Comment by andrewbird** [comment]
Which is good that it supports int21/7303 internally, but crap that it wants to do a DOS version check first. https://www.delorie.com/bin/cvsweb.cgi/djgpp/src/libc/compat/sys/vfs/statfs.c?rev=1.10
