### ISSUE TITLE
Suggestion: Make a PPA for Debian

### ISSUE THREAD

**Issue by TerryTRSPanda** [dosemu2/comcom32#70]
I'm having a lot of trouble setting up Dosemu2 for a buildtime dependency for an ia-16 toolchain and I'm having a difficult time chasing down where I'm supposed to put freecom or commandcom32 and in sparing myself from headaches and other debian users as well to making it feasible to avoid "FrankenDebian" with a lot of make installs, I'm suggesting a Debian PPA not just for me, but for others as well.

**Comment by stsp** [comment]
Debian probably has bsd-compatible install,
and not a gnu install.
I added a possible fix.
Please update and try again.

**Comment by andrewbird** [comment]
> install: cannot create directory '/usr/share/comcom32': No such file or directory

Suggests to me that /usr/share doesn't exist.

**Comment by stsp** [comment]
Doesn't matter because:
```
       -D     create  all  leading  components of DEST except the last, or all
              components of --target-directory, then copy SOURCE to DEST
```
It creates with parent.
Obviously an attempt to create anything
wasn't done.

**Comment by andrewbird** [comment]
Mmm, how weird!

**Comment by stsp** [comment]
Not so much given that I already switched
fdpp and dosemu2 to the bsd-compatible
syntax of install. comcom32 was forgotten.

**Comment by TerryTRSPanda** [comment]
The issues with building in Debian in the replies like the ones between my last reply and this reply is why a Debian PPA might be a good idea. I imagine if issues like this didn't happen with me, they would eventually happen with someone else and they probably happened to others before and just went unreported. I've known how to compile software for over 14 years and I never had an account on any revision control based website.

**Comment by TerryTRSPanda** [comment]
> Debian probably has bsd-compatible install, and not a gnu install. I added a possible fix. Please update and try again.

Oh you were telling me to rebuild, sorry just woke up. It worked and thanks. I've also heard a big problem with assuming GNU and not actual POSIX standards is stuff like this happens on BSD. GNU doesn't really adhere to the UNIX Philosophy.

**Comment by TerryTRSPanda** [comment]
I got a build error on dosemu

`---------------------------------DONE Installing-------------------------------

  - You can type 'dosemu' to run DOSEMU2.
make[2]: Leaving directory '/home/user/src/dosemu2/build/src'
make[1]: Leaving directory '/home/user/src/dosemu2/build'
   dh_install -O--builddirectory=build
   dh_installdocs -O--builddirectory=build
   dh_installchangelogs -O--builddirectory=build
   dh_installman -O--builddirectory=build
   dh_installinit -O--builddirectory=build
   dh_installsystemduser -O--builddirectory=build
   dh_perl -O--builddirectory=build
   dh_link -O--builddirectory=build
   dh_installxfonts -O--builddirectory=build
   dh_strip_nondeterminism -O--builddirectory=build
   dh_compress -O--builddirectory=build
   dh_fixperms -O--builddirectory=build
   dh_missing -O--builddirectory=build
   dh_strip -O--builddirectory=build
   dh_makeshlibs -O--builddirectory=build
   debian/rules override_dh_shlibdeps
make[1]: Entering directory '/home/user/src/dosemu2'
dh_shlibdeps -X.so
dh_shlibdeps -- -dRecommends -pshlibs-
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/fdpp/libfdpp.so.32.9 (used by debian/dosemu2/usr/lib/dosemu/libplugin_fdpp.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/dosemu2.substvars -dRecommends -pshlibs- debian/dosemu2/usr/bin/mkfatimage16 debian/dosemu2/usr/bin/dosdebug debian/dosemu2/usr/bin/dosemu.bin debian/dosemu2/usr/lib/dosemu/libplugin_fluidsynth.so debian/dosemu2/usr/lib/dosemu/libplugin_fdpp.so debian/dosemu2/usr/lib/dosemu/libplugin_json.so debian/dosemu2/usr/lib/dosemu/libplugin_sdl.so debian/dosemu2/usr/lib/dosemu/libplugin_libao.so debian/dosemu2/usr/lib/dosemu/libplugin_console.so debian/dosemu2/usr/lib/dosemu/libplugin_XKmaps.so debian/dosemu2/usr/lib/dosemu/libplugin_alsa.so debian/dosemu2/usr/lib/dosemu/libplugin_term.so debian/dosemu2/usr/lib/dosemu/libplugin_ladspa.so debian/dosemu2/usr/lib/dosemu/libplugin_gpm.so debian/dosemu2/usr/lib/dosemu/libplugin_X.so debian/dosemu2/usr/lib/dosemu/libplugin_lpt.so debian/dosemu2/usr/lib/dosemu/libplugin_slirp.so returned exit code 25
dh_shlibdeps: error: Aborting due to earlier error
make[1]: *** [debian/rules:20: override_dh_shlibdeps] Error 25
make[1]: Leaving directory '/home/user/src/dosemu2'
make: *** [debian/rules:7: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
make: *** [Makefile:65: deb] Error 29
`

**Comment by andrewbird** [comment]
> The issues with building in Debian in the replies like the ones between my last reply and this reply is why a Debian PPA might be a good idea.

I don't think anyone is questioning that. Ubuntu provides its Launchpad to create the PPA, Fedora has copr, so if Debian has something similar I'd be happy to add the receipe to make it happen. As yet I know of no Debian equivalent?

**Comment by TerryTRSPanda** [comment]
> > The issues with building in Debian in the replies like the ones between my last reply and this reply is why a Debian PPA might be a good idea.
> 
> I don't think anyone is questioning that. Ubuntu provides its Launchpad to create the PPA, Fedora has copr, so if Debian has something similar I'd be happy to add the receipe to make it happen. As yet I know of no Debian equivalent?

Debian has PPAs, Debian just has the old way. Debian doesn't use apt-add-repo, you have to manually edit a sources.list config file and tell apt to add a key file so apt doesn't yell at you for adding an unsigned repo. It will work without a key though, apt will just tell the user it's a bad idea.

**Comment by stsp** [comment]
```
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/fdpp/libfdpp.so.32.9 (used by debian/dosemu2/usr/lib/dosemu/libplugin_fdpp.so)
Hint: check if the library actually comes from a package.
```

This probably means dh_makeshlibs didn't
work when fdpp package was built.
@skitt maybe you can hint me what is it?

**Comment by andrewbird** [comment]
Creating a Debian repo is not a great task, but populating it with the packages is. That's why I was looking for a solution like Ubuntu's Launchpad which tracks our git repositories, builds and uploads packages to the PPA several times per day.

**Comment by TerryTRSPanda** [comment]
Maybe for future reference we can request Debian include Dosemu2 in future repos. But I'd settle for pre-built debs

**Comment by skitt** [comment]
> ```
> dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/fdpp/libfdpp.so.32.9 (used by debian/dosemu2/usr/lib/dosemu/libplugin_fdpp.so)
> Hint: check if the library actually comes from a package.
> ```
> 
> This probably means dh_makeshlibs didn't work when fdpp package was built. @skitt maybe you can hint me what is it?

It did work, but the build picked up `libfdpp` from `/usr/local/lib/fdpp` rather than `/usr/lib/fdpp`. Deleting `/usr/local/lib/fdpp` and restarting the `dosemu2` build should fix things.

**Comment by stsp** [comment]
Ah, good catch!
I need to add that  because fdpp uses
rpath, rebuilding dosemu2 package
might be needed after `sudo make uninstall`
of fdpp.

**Comment by TerryTRSPanda** [comment]
So I tried removing fdpp and got another build error with dosemu and I rebuilt fdpp and got the old build error back.
