### ISSUE TITLE
disable CI for entire branch

### ISSUE THREAD

**Issue by stsp** [dosemu2/comcom32#72]
Hi Andrew, would it be possible to invent
some way to disable the CI for the branches?
For example by associating the `no_ci`
git tag name with some commit belonging
to that branch? Or by some other way you
can think of.

I am committing quite frequently to the
thunkgen branch (because I can already
compile the 64bit version of comcom32,
of course it doesn't work yet though),
and every time I get the build failure as
it won't compile on CI for quite long from
now.

**Comment by andrewbird** [comment]
The easiest way for now is to make a separate commit that removes `https://github.com/dosemu2/comcom32/blob/master/.github/workflows/ci-build.yml` . After you get to the stage where you want the branch testing again, just drop that commit.

**Comment by stsp** [comment]
OKey. :)
