### ISSUE TITLE
Litil Divil says it needs 580k base memory to run

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/comcom32#73]
**Describe the bug**
![Screenshot_20220917_213642](https://user-images.githubusercontent.com/877112/190873791-64b167fd-bdd8-4fce-8707-09cf2fed5adb.png)

According to `mem /p` there should be more than enough :)

**To Reproduce**
Just run the game.

**Attach program/game binaries or provide an URL**
[divil.tar.gz](https://github.com/dosemu2/dosemu2/files/9592495/divil.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9592487/boot.log)

**A regression?**
unknown

**Comment by stsp** [comment]
Fixed with f3c4a32d

**Comment by jschwartzenberg** [comment]
Yeah seems to work! I don't get how that game should be played either...

Btw. maybe it would be good to print a message when the exepack detection is triggered. I think it will still be visible just long enough even if it disappears quickly when a game switches to graphical mode. An environment variable could be used to enable the prompt as well before continuing. (Like in the special version you provided me some time ago.) What do you think? It might help slightly in getting issues created below comcom32 instead of dosemu2 when this message is printed and something (still) goes wrong.

**Comment by stsp** [comment]
There will be no such problems any more.
Note that it was fixed long ago, I just checked
it today. Also I added a check today to disable
the exepack detection if HMA is not enabled,
which is by default.
So these were the bugs, which are fixed.
This problem won't re-surface.
