### ISSUE TITLE
Unable to manually set time or date with comcom32

### ISSUE THREAD

**Issue by nromey** [dosemu2/comcom32#83]
Per stsp, submitting this bug. see #80 
 #symptoms: unable to set time or date with comcom32.
I've tried setting time bios settings and regardless of the setting (bios" etc. typing "date" or "time" does not allow me to set time or date.  dosemu uses freecom, and it's possible to set time there.
Steps to reproduce:
1. boot dosemu2+FDPP
2. run the time command
3. run the date command.  This will display time and date but not ask for a value to set
4. run date 01/01/1999 to set the datt. No output is detected
5. run date again, and you'll notice that date remains the same ragardless the time set variable in dosemu.conf
6. ru freecom.exe and follow steps 1 through 4
7. Date is set and can be verified.
Please let me know if this is enough information to proceed.

**Comment by stsp** [comment]
But I already fixed that in #81

**Comment by nromey** [comment]
Ah Sorry about that, I didn’t see you’d fixed it.

 

NER
