### ISSUE TITLE
Continue on error?

### ISSUE THREAD

**Issue by haenschen** [dosemu2/comcom32#85]
When encountering an error, batch files abort. E.g.
```
cd testdir
Directory does not exist - testdir
Batch file aborted - C:\USERHOOK.bat, line 2
```
Freecom and ms-dos command.com continue on error with the next line.

Maybe this is intended behaviour but imho there should be an option to set `ContinueOnError=true`. Some older dos program might make use of .bat files to set options or other things and will fail when encountering one faulty line.

**Comment by stsp** [comment]
Should now be fixed.
